services:
  db:
    ports:
      - "127.0.0.1:5433:5432"
    networks:
      - database
      - web
  app:
    environment:
      APP_ENV: development
      OWNER_PASSWORD: ${OWNER_PASSWORD:-demo123}
      TEAM_LEADER_PASSWORD: ${TEAM_LEADER_PASSWORD:-demo1234}
      RESELLER_PASSWORD: ${RESELLER_PASSWORD:-demo1234}
